<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <!-- NuGet package versions -->
    <AkkaVersion>1.5.31</AkkaVersion>
    <OpenTelemetryVersion>1.14.0</OpenTelemetryVersion>
    <MicrosoftExtensionsVersion>8.0.0</MicrosoftExtensionsVersion>
  </PropertyGroup>

  <!-- Akka.NET dependencies -->
  <ItemGroup>
    <PackageVersion Include="Akka" Version="$(AkkaVersion)" />
  </ItemGroup>

  <!-- Microsoft.Extensions dependencies -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="$(MicrosoftExtensionsVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="$(MicrosoftExtensionsVersion)" />
  </ItemGroup>

  <!-- OpenTelemetry dependencies -->
  <ItemGroup>
    <PackageVersion Include="OpenTelemetry" Version="$(OpenTelemetryVersion)" />
    <PackageVersion Include="OpenTelemetry.Exporter.Console" Version="$(OpenTelemetryVersion)" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="$(OpenTelemetryVersion)" />
  </ItemGroup>

  <!-- SourceLink support -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
  </ItemGroup>
</Project>
