<Project>
  <PropertyGroup>
    <Copyright>Copyright © 2015-$([System.DateTime]::Now.Year) Akka.NET Team</Copyright>
    <Authors>Akka.NET Team</Authors>
    <Tags>akka;akkadotnet;opentelemetry;tracing;logging;distributed-tracing</Tags>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <VersionPrefix>1.0.0</VersionPrefix>
  </PropertyGroup>

  <!-- GitHub SourceLink -->
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
  </ItemGroup>

  <!-- NuGet package properties -->
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)\akkalogo.png" Pack="true" PackagePath="\" />
    <None Include="$(MSBuildThisFileDirectory)\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <PropertyGroup>
    <PackageReleaseNotes>1.0.0 January 12 2026 - Initial proof of concept for log/trace correlation</PackageReleaseNotes>
    <PackageTags>akka;actors;opentelemetry;tracing;logging;distributed-tracing;correlation</PackageTags>
    <PackageProjectUrl>https://github.com/akkadotnet/akka.net-log-trace-correlation-POC</PackageProjectUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageIcon>akkalogo.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
</Project>
